Add player and weapon color funcs to shared
CFC-Servers/cfc_sf_lib pull request #12
Opened 2021-08-03 19:52 UTC by banoargeek

Starfall currently lacks player methods for getting the Player and Weapon colors the same way E2 does. It just uses built-in Garry's Mod methods.

2021-08-03 20:21 UTC, samuelWilliams99 commented
hey @plally can you review this please, it'd make me sooooo happy

2021-08-04 00:42 UTC, plally approved these changes

2021-08-06 00:56 UTC, Syvil commented
I think colors are one of the things you are meant to wrap when returning.
instance.Types.Color.Wrap( Color ) is the function for that.

2021-08-06 03:58 UTC, plally requested changes
good catch @Syvil, should be looked into before merging

2021-08-06 20:23 UTC, banoargeek commented
@plally It says you requested a change but I cannot seem to see it.

2021-08-06 20:23 UTC, banoargeek commented
Oh, my bad. Let me read up on the comment thread. :)

2021-08-06 20:23 UTC, wrefgtzweve commented
> @plally It says you requested a change but I cannot seem to see it.

![image](https://user-images.githubusercontent.com/69946827/128567219-df4b7884-bb99-4ccf-acbc-66d836ae9b61.png)

2021-08-06 20:23 UTC, banoargeek commented
Thank you @Syvil, I'll rectify that

2021-08-06 20:24 UTC, banoargeek commented
Ty @Redox

2021-08-06 20:38 UTC, banoargeek commented
Apologies for the duplicate commit, lmao

2021-08-06 20:39 UTC, banoargeek commented
Okay, I messed up in a way that I have not yet encountered. I'll fix it with a commit.

2021-08-06 20:42 UTC, banoargeek commented
Please let me know if my local variables are defined satisfactorily.

2021-08-07 00:58 UTC, Syvil commented
If you are going to localize instance.Types, you could instead localize instance.Types.Color.Wrap, which would remove an extra two table lookups from each function.
`colwrap( ply:GetWeaponColor() )` instead of `types.Color.Wrap( ply:GetWeaponColor() )`

2021-08-07 01:11 UTC, plally requested changes

2021-08-07 01:11 UTC, plally commented on lua/starfall/libs_sh/ply.lua
> +    return
you aren't returning anything here

2021-08-07 01:12 UTC, plally commented
I agree with syvil, I think localizing color would be good. `local colorWrap = types.Color.Wrap`
You could also take just do `return colorWrap( color )` instead  of using a local variable

2021-08-07 19:59 UTC, banoargeek commented
Agh, I must be having trouble paying attention on account of getting my covid shot, let me re-readdress that.

2021-08-07 20:04 UTC, banoargeek commented
That should address the current concerns.

2021-08-07 20:40 UTC, plally approved these changes

2021-08-07 21:08 UTC, merged